-- MySQL Script generated by MySQL Workbench
-- Wed Mar 18 22:48:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_helpdesk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_helpdesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_helpdesk` DEFAULT CHARACTER SET utf8mb4 ;
USE `bd_helpdesk` ;

-- -----------------------------------------------------
-- Table `bd_helpdesk`.`t_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_helpdesk`.`t_persona` (
  `id_persona` INT(11) NOT NULL AUTO_INCREMENT,
  `paterno` VARCHAR(245) NULL DEFAULT NULL,
  `materno` VARCHAR(245) NULL DEFAULT NULL,
  `nombre` VARCHAR(245) NULL DEFAULT NULL,
  `fecha_nacimiento` VARCHAR(245) NULL DEFAULT NULL,
  `sexo` VARCHAR(2) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(245) NULL DEFAULT NULL,
  `fechaInsert` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_helpdesk`.`t_cat_equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_helpdesk`.`t_cat_equipo` (
  `id_equipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(245) NOT NULL,
  `descripcion` VARCHAR(245) NULL DEFAULT NULL,
  PRIMARY KEY (`id_equipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_helpdesk`.`t_asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_helpdesk`.`t_asignacion` (
  `id_asignacion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_persona` INT(11) NOT NULL,
  `id_equipo` INT(11) NOT NULL,
  `marca` VARCHAR(245) NULL DEFAULT NULL,
  `modelo` VARCHAR(245) NULL DEFAULT NULL,
  `color` VARCHAR(245) NULL DEFAULT NULL,
  `descripcion` VARCHAR(245) NULL DEFAULT NULL,
  `memoria` VARCHAR(245) NULL DEFAULT NULL,
  `disco_duro` VARCHAR(245) NULL DEFAULT NULL,
  `procesador` VARCHAR(245) NULL DEFAULT NULL,
  PRIMARY KEY (`id_asignacion`),
  INDEX `fkPersona_idx` (`id_persona` ASC) VISIBLE,
  INDEX `fkequipoAsignacion_idx` (`id_equipo` ASC) VISIBLE,
  CONSTRAINT `fkPersonaAsignacion`
    FOREIGN KEY (`id_persona`)
    REFERENCES `bd_helpdesk`.`t_persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkequipoAsignacion`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `bd_helpdesk`.`t_cat_equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_helpdesk`.`t_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_helpdesk`.`t_roles` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_helpdesk`.`t_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_helpdesk`.`t_usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `id_rol` INT(11) NOT NULL,
  `id_persona` INT(11) NOT NULL,
  `usuario` VARCHAR(245) NOT NULL,
  `password` VARCHAR(245) NOT NULL,
  `ubicacion` TEXT NULL DEFAULT NULL,
  `activo` INT(11) NOT NULL DEFAULT 1,
  `fecha_insert` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario` (`usuario` ASC) VISIBLE,
  INDEX `fk_usuario_rol` (`id_rol` ASC) VISIBLE,
  INDEX `fk_usuario_persona` (`id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `bd_helpdesk`.`t_persona` (`id_persona`),
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `bd_helpdesk`.`t_roles` (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;
+


-- -----------------------------------------------------
-- Table `bd_helpdesk`.`t_reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_helpdesk`.`t_reportes` (
  `id_reporte` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_equipo` INT(11) NOT NULL,
  `id_usuario_tecnico` INT(11) NULL DEFAULT NULL,
  `descripcion_problema` TEXT NOT NULL,
  `solucion_problema` TEXT NULL DEFAULT NULL,
  `estatus` INT(11) NOT NULL DEFAULT 1,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_reporte`),
  INDEX `fkUsuarioReporte` (`id_usuario` ASC) VISIBLE,
  INDEX `fkEquipoReporte` (`id_equipo` ASC) VISIBLE,
  CONSTRAINT `fkEquipoReporte`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `bd_helpdesk`.`t_cat_equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkUsuarioReporte`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_helpdesk`.`t_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
